website/ohara/urls.py
from django.urls import path

from . import views

app_name = 'ohara'
urlpatterns = [
    path('', views.upload, name = 'upload'),
    path('text_handler/', views.text_handler, name = 'text_handler'),
    path('success/', views.success, name = 'success'),
    path('repeat_entry_warning/<str:fname>/', views.repeat_entry_warning, name = 'repeat_entry_warning'),
    path('return_to_upload/', views.return_to_upload, name = "return_to_upload"),
    path('view_in_notion/', views.view_in_notion, name = "view_in_notion"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ohara/', include('ohara.urls')),
    path('admin/', admin.site.urls),
]

website/ohara/models.py
from django.db import models

# Create your models here.

website/ohara/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

website/ohara/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from src.ohara import Ohara
import os
# Create your views here.

def upload(request):
    return render(request, 'ohara/upload.html', {})

def text_handler(request):
    bibDir = './ohara/bib/'
    ohara = Ohara(bibDir)
    bibtex = request.POST['bibtex']
    lines = bibtex.split('\n')
    firstline = lines[0]
    if firstline.find('/') >= 0:
        fname = firstline[firstline.find("/")+1:firstline.find(",")]+'.bib'
    else: 
        fname = firstline[firstline.find("{")+1:firstline.find(",")]+'.bib'
    fpath = bibDir+fname
    file_exist = False
    for dirName, subdirList, fileList in os.walk(ohara.rootDir):
        if fname in fileList:
            file_exist = True
            break
    if file_exist:
        print(reverse('ohara:repeat_entry_warning', args = (fname,)))
        return HttpResponseRedirect(reverse('ohara:repeat_entry_warning', args = (fname,)))
    else:
        with open(fpath, 'w', encoding = 'utf-8') as f:
            f.write(bibtex)
        ohara.add_entry_from_file(fpath)
    return HttpResponseRedirect(reverse('ohara:success'))

def repeat_entry_warning(request, fname):
    warning_msg = fname + " is already in Ohara!"
    return render(request, 'ohara/warning.html', {
            'warning_msg': warning_msg,
        })

def success(request):
    return render(request, 'ohara/success.html', {})

def return_to_upload(request):
    return HttpResponseRedirect(reverse('ohara:upload'))

def view_in_notion(request):
    ohara = Ohara('.')
    return HttpResponseRedirect(ohara.get_notion_page_url())

website/ohara/templates/ohara/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error!</h1>
</body>
</html>

website/ohara/templates/ohara/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h1>Success!</h1>
    <form action="{%url 'ohara:return_to_upload' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Return to Upload Page">
    </form>
    <div><a href="{%url 'ohara:view_in_notion' %}">View in Notion</a></div>
</body>
</html>

website/ohara/templates/ohara/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ohara Uploader</title>
</head>
<body>
    <h1>Ohara Uploader</h1>
    <form action="{% url 'ohara:text_handler' %}" method="post">
        {% csrf_token %}
        <label for="bibtex">Citation in Bibtex Format:</label>
        <div>
            <textarea name="bibtex" id="bibtex" cols="30" rows="10"></textarea>
        </div>
        <!-- <input type="text" name="bib-text" id="bib-text"> -->
        <input type="submit" value="Submit">
    </form>
</body>
</html>

website/ohara/templates/ohara/warning.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Warning!</title>
</head>
<body>
    <h1>Warning!</h1>
    <div>{{ warning_msg }}</div>    
</body>
</html>